### ISSUE TITLE
option to view enclosures button in the article list 

### ISSUE THREAD

**Issue by P0bo** [SkyD666/AniVu#10]
it will be convenient to have this 
![Screenshot_2024-04-16-00-00-29-16_6de1e84f9daf512b0c3cf0ac2d20418d](https://github.com/SkyD666/AniVu/assets/154865357/8d74ca51-f2ba-4c59-bbf6-0249c296a67d)
button in the article list for easy access directly saving time 
![Screenshot_2024-04-16-00-00-56-09_6de1e84f9daf512b0c3cf0ac2d20418d](https://github.com/SkyD666/AniVu/assets/154865357/1c22bb6c-2dda-4cc2-b529-504c690cd50a)

**Comment by SkyD666** [comment]
https://github.com/SkyD666/AniVu/actions/runs/8708606371

**Comment by P0bo** [comment]
> https://github.com/SkyD666/AniVu/actions/runs/8708606371

I have seen and used it just now; however, it shows three dots. 1. Clicking them shows the "Enclosures" button, 2. Clicking the button shows the download button, and 3. Clicking it starts the download.

Previously, 1. Clicking an item from the feed opened the article which shows the "Enclosures" button at the bottom, 2. Clicking the button showed the download button, and 3. Clicking it started the download.

As you can see, both steps take the same amount of clicks (3 clicks), which is not a practical improvement. I suggest showing the "Enclosures" button directly instead of the three dots in the article list, which will reduce one click. Also, we won't have to open an empty article. (Most RSS feeds provide only enclosures except for bangumi.moe, so we don't need to open the article almost all the time.)
>what i wanted to suggest 
![1713302399394](https://github.com/SkyD666/AniVu/assets/154865357/5d9b16cc-bb56-4f0b-ae0f-26aa298033b7)

>clicking the button will directly open the download option 
![1713302399752](https://github.com/SkyD666/AniVu/assets/154865357/10e8ea47-603e-4810-99ed-d819b725c4f5)

**Comment by P0bo** [comment]
Also, I have noticed something: clicking the "download" button doesn't close the download window. It should close the download window. Additionally, it should indicate a "downloading" icon when an enclosure from an article is downloading instead of the "enclosures" button, and a "downloaded" icon when an enclosure from an article is already downloaded. This will reduce confusion when downloading from multiple articles and prevent spamming the download button, saving more time because we can't see any downloaded/downloading indicator beside the article.

**Comment by SkyD666** [comment]
One question is: If I don't use the menu and I want to display other operations on this page, what should I do?

**Comment by P0bo** [comment]
> One question is: If I don't use the menu and I want to display other operations on this page, what should I do?

U use longpress actions . i.e Long pressing the article will give a pop up of other options

**Comment by P0bo** [comment]
Swipe actions are useful for quick operations

**Comment by SkyD666** [comment]
In this case, it seems better to just swipe left to display the enclosures

**Comment by Luffyirl** [comment]
> In this case, it seems better to just swipe left to display the enclosures


> In this case, it seems better to just swipe left to display the enclosures

Just make a tab in settings called interaction and let ppl select between swipe and enclosure button like @p0bo said.
I prefer buttons over swipe coz i have small hands and i can reach top articles ,let alone swipe 
>example - [ReadYou](https://github.com/Ashinch/ReadYou)
![Screenshot_2024-04-17-10-40-27-422_me ash reader](https://github.com/SkyD666/AniVu/assets/128812994/241b5848-3edc-468f-9fdb-31aedceeaf5c)

**Comment by Ripl0gic** [comment]
> Also, I have noticed something: clicking the `"download"` button doesn't close the download window. It should close the download window. Additionally, it should indicate a `"downloading"`icon when an enclosure from an article is downloading instead of the `"enclosures"` button, and a `"downloaded"` icon when an enclosure from an article is already downloaded. This will reduce confusion when downloading from multiple articles and prevent spamming the download button, saving more time because we can't see any downloaded/downloading indicator beside the article.

Three dots on repeat looks ugly tbh. The enclosure button which will changed to downloading indicator and downloaded indicator will be better.

**Comment by P0bo** [comment]
> > In this case, it seems better to just swipe left to display the enclosures
> 
> Just make a tab in settings called interaction and let ppl select between swipe and enclosure button like @P0bo said. I prefer buttons over swipe coz i have small hands and i can reach top articles ,let alone swipe
> 
> > example - [ReadYou](https://github.com/Ashinch/ReadYou)
> > ![Screenshot_2024-04-17-10-40-27-422_me ash reader](https://private-user-images.githubusercontent.com/128812994/323085095-241b5848-3edc-468f-9fdb-31aedceeaf5c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzIxNjgsIm5iZiI6MTcxMzMzMTg2OCwicGF0aCI6Ii8xMjg4MTI5OTQvMzIzMDg1MDk1LTI0MWI1ODQ4LTNlZGMtNDY4Zi05ZmRiLTMxYWVkY2VlYWY1Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QwNTMxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWJmZDcxZTM2ZTk5NGQ2NjgyZTUxMTRhOGNkYzMwNjZiMDYzZTdmYjlkMTI5ZjRkMjUxMzUyMzJhYmZmZWNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ULBaLchdTyDmHfu9wBY8x51SNMkNeGrYMTsu-PwmtDE)

Interesting , I was confused between swipe and the enclosure button , while i prefer swipe on my phone but i like having the enclosure button on my tablet because swiping can be sometimes difficult on big screen  .


 The concept i shared had the buttons from the article tab cut and paste , i thing a minimal version or that button or a smaller version of that button will look cleaner .

**Comment by P0bo** [comment]
> Something like This 
![1713332643361.png](https://github.com/SkyD666/AniVu/assets/154865357/ad7285ec-5643-46ab-aeff-7b401a334278)



>instead of the normal button 
![1713332643445.png](https://github.com/SkyD666/AniVu/assets/154865357/997aa5ca-61a2-4f55-b421-63f7cd4ab25c)

**Comment by SkyD666** [comment]
I think readyou is a good example, swipe can show enclosures and more options menu also has an item that can show enclosures

**Comment by P0bo** [comment]
> I think readyou is a good example, swipe can show enclosures and more options menu also has an item that can show enclosures

yeh its a good example , and  if u implement this(swipe for enclosure ) please remove the 3 dots or give an option to hide the 3 dots for the ppl who don't want three dots. Also please add a configurable tap action , example -> tap action  : open article or show enclosure , and swipe action : open article or show enclosure , as it will be great since some  ppl may don't want to open article and just view and download the enclosure and be done with it .

**Comment by SkyD666** [comment]
https://github.com/SkyD666/AniVu/actions/runs/8783737264
