### ISSUE TITLE
Use mpv based player

### ISSUE THREAD

**Issue by P0bo** [SkyD666/AniVu#11]
Mpv player is a really great player and the aniyomi version of mpv player looks a lot better than official mpv , it also has material ui support. 

aniyomi-https://github.com/aniyomiorg/aniyomi

**Comment by SkyD666** [comment]
There are some problems: 1. aniyomi-mpv-lib is not a library, so we need more work to use it; 2. aniyomi-mpv-lib includes native code, makes apk size larger

**Comment by P0bo** [comment]
is there any way to use mpv based player ? customisation is really good in mpv , because of mpv.conf  , also it supports stats for nerds which is really helpful for cross checking quality of episodes. And i use my tablet with keyboard and mpv allows customising almost every key input.conf

**Comment by Luffyirl** [comment]
Agree , mpv provides a hefty amount of customisation and personalisation.Its not only good for tablet but also phones . And it uses significantly less resources from phone than other players saving a lot of battery and ram. U can even specify mac  how much forword or backward ram it should use in mpv.

**Comment by P0bo** [comment]
> Agree , mpv provides a hefty amount of customisation and personalisation.Its not only good for tablet but also phones . And it uses significantly less resources from phone than other players saving a lot of battery and ram. U can even specify max how much forword or backward ram it should use in mpv.


Especially in AniVu, the subtitles look ugly, and there's no way to customize the border size/color, shadow color/offset, font size/color, etc. And the lack of keyboard support, let alone customizable keybindings. Don't get me wrong, I love AniVu (I loved it when I found the repo and still do now). I really thank and respect the dev for making the app. It's my humble request to please consider using an mpv-based player.

**Comment by Luffyirl** [comment]
Fair enough . Also Kudos to the developer for such an awesome app! ..

**Comment by SkyD666** [comment]
> > Agree , mpv provides a hefty amount of customisation and personalisation.Its not only good for tablet but also phones . And it uses significantly less resources from phone than other players saving a lot of battery and ram. U can even specify max how much forword or backward ram it should use in mpv.
> 
> 
> Especially in AniVu, the subtitles look ugly, and there's no way to customize the border size/color, shadow color/offset, font size/color, etc. And the lack of keyboard support, let alone customizable keybindings. Don't get me wrong, I love AniVu (I loved it when I found the repo and still do now). I really thank and respect the dev for making the app. It's my humble request to the dev to please consider using an mpv-based player.
> 
> 
> 
> 

Subtitle effects are indeed a big problem because exoplayer does not support them.

https://github.com/google/ExoPlayer/issues/8435

**Comment by SkyD666** [comment]
In addition, thank you for your valuable suggestions, but I am busy with my studies recently, so the update frequency may not be too frequent.

**Comment by SkyD666** [comment]
For the mpv player, I'll learn more about it.

**Comment by P0bo** [comment]
> In addition, thank you for your valuable suggestions, but I am busy with my studies recently, so the update frequency may not be too frequent.

Best of luck with ur studies .No problems with update frequency .

**Comment by SkyD666** [comment]
I found that mpv doesn't seem to be able to use a custom data source (such as InputStream)

**Comment by Luffyirl** [comment]
> I found that mpv doesn't seem to be able to use a custom data source (such as Java InputStream)
> 
> This is bad for playing torrents

doesn't anivu just play files after downloading ? if #12 is implemented the app will play the fies inside that specific folder after they they downloaded , mpv wont have problem playing such files . And if u want t implement torrent streaming (without downloading the torrent ) u will need webtorrent hook for mpv wich isnt available for android devices , another way to is to implement torrent server but that will increase the app side significantly .

**Comment by P0bo** [comment]
> > I found that mpv doesn't seem to be able to use a custom data source (such as Java InputStream)
> > This is bad for playing torrents
> 
> Doesn't AniVu just play files after downloading? If #12 is implemented, the app will play the files inside that specific folder after they are downloaded; mpv won't have a problem playing such files. And if you want to implement torrent streaming (without downloading the torrent), you will need a webtorrent hook for mpv, which isn't available for Android devices. Another way is to implement a torrent server, but that will significantly increase the app's size.
> 
> Only app that has implemented torrent streaming which is usable is stremio , no alternatives what so ever for android , all the other apps that tried have either failed or didnt meet the expectatins .


@Luffyirl Stremio uses libVLC on Android, if I recall correctly. There's an app called [Kuukiyomi](https://github.com/LuftVerbot/kuukiyomi) that uses libmpv with ffmpeg kit (it uses same player since it's a fork of Aniyomi) which supports streaming torrents, but their server is not nearly as good or buffer-free as Stremio.

**Comment by SkyD666** [comment]
Can you give the Stremio android repository? I can't find it.

**Comment by P0bo** [comment]
> Can you give the Stremio android repository? I can't find it.

Stremio android is not open source :

>reason (From a stremio dev)
>"The reason for the mobile app itself not being open source is that we have an agreement with a partner company and an investor preventing us from publishing it."

**Comment by Luffyirl** [comment]
>![1713637442598](https://github.com/SkyD666/AniVu/assets/128812994/6bfedeb9-7ea4-4509-b8ef-912001e1b0a0)

>damn i thought most ppl dont even use mpv .

**Comment by SkyD666** [comment]
Actually, I have a question, why not use an external player to open the video?

![Screenshot_20240421_082744_edit_126683168353064.jpg](https://github.com/SkyD666/AniVu/assets/32453770/571bb6b1-89b0-4367-9e23-f360f0103547)

**Comment by Luffyirl** [comment]
1. I have been doing that with Flud and LibreTorrent; both of them support RSS feeds with auto-downloading.
2. I do use VLC and mpv from time to time, but both have ugly UI and don't support Material You.
3. Doesn't that just defy the whole point of the app?
   > All-in-one Android app for anime RSS, BitTorrent dl & play.
4. Won't it be just the same as any other torrent app out there that has feed support?

**Comment by P0bo** [comment]
> Actually, I have a question, why not use an external player to open the video?
> 
> ![Screenshot_20240421_082744_edit_126683168353064.jpg](https://private-user-images.githubusercontent.com/32453770/324213439-571bb6b1-89b0-4367-9e23-f360f0103547.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzA2NzAsIm5iZiI6MTcxMzY3MDM3MCwicGF0aCI6Ii8zMjQ1Mzc3MC8zMjQyMTM0MzktNTcxYmI2YjEtODliMC00MzY3LTllMjMtZjM2MGYwMTAzNTQ3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDAzMzI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2N2Q4NjY5ZjQ0ZGE4MTMyOTg5MTU0MjE3ODBiOWZlNmJiMWJjOTg4NzM4ZWUyOWU2MjNkYjdiODA0NjMzNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hZ3kM1QGxq06rFwTivbcbjCBEJP4QuHVRKxc5ofxgmI)



I actually do that , i just love this app ❤️ and want the in-app player to get better .And since this app even supports playing other files , i have plans to use it as my main player but the in-app player isnt good enough for that yet .

**Comment by SkyD666** [comment]
> 1. I have been doing that with Flud and LibreTorrent; both of them support RSS feeds with auto-downloading.
> 2. I do use VLC and mpv from time to time, but both have ugly UI and don't support Material You.
> 3. Doesn't that just defy the whole point of the app?
>    > All-in-one Android app for anime RSS, BitTorrent dl & play.
> 4. Won't it be just the same as any other torrent app out there that has feed support?

Since mpv cannot support custom data sources, we plan to continue using exoplayer. Using an external player to open videos is only an option for users who feel that the built-in player experience is not good.

**Comment by SkyD666** [comment]
On the other hand, judging from the recent situation of playing torrent, most of the time, the torrent resources are poor and often cannot be loaded, so whether to support direct play torrent is also a question that needs to be considered.

**Comment by Ripl0gic** [comment]
> > 1. I have been doing that with Flud and LibreTorrent; both of them support RSS feeds with auto-downloading.
> > 2. I do use VLC and mpv from time to time, but both have ugly UI and don't support Material You.
> > 3. Doesn't that just defy the whole point of the app?
> >    > All-in-one Android app for anime RSS, BitTorrent dl & play.
> > 4. Won't it be just the same as any other torrent app out there that has feed support?
> 
> Using an external player to open videos is only an option for users who feel that the built-in player experience is not good.
> 
> On the other hand, judging from the recent situation of playing torrent, most of the time, the torrent resources are poor and often cannot be loaded, so whether to support directly playing torrent is also a question that needs to be considered.
> 
> I posted a vote in the telegram group

Can someone please sent the result of the poll ? I'm not on teligram

**Comment by Luffyirl** [comment]
![Screenshot_2024-04-23-01-33-20-920_org.telegram.messenger-edit.jpg](https://github.com/SkyD666/AniVu/assets/128812994/3409310a-9816-4a90-ac6b-1e65e7b40c64)

**Comment by Luffyirl** [comment]
@SkyD666 Downloaded beta24 just now . When i enable subtitle styling the subtitle disappears , please investigate it .

**Comment by SkyD666** [comment]
> @SkyD666 Downloaded beta24 just now . When i enable subtitle styling the subtitle disappears , please investigate it .

The cause of this problem is unknown and cannot be solved at this time, help from others is needed

**Comment by Luffyirl** [comment]
> > @SkyD666 Downloaded beta24 just now . When i enable subtitle styling the subtitle disappears , please investigate it .
> 
> The cause of this problem is unknown and cannot be solved at this time, help from others is needed

Also most of the working configs are not working in anivu that work in official mpv amd aniyomi mpv , for example only sub-ass-* high level comands work sub-* dont work also osd comands don't work , for example osd-level and osd-fractions

**Comment by SkyD666** [comment]
> > > @SkyD666 Downloaded beta24 just now . When i enable subtitle styling the subtitle disappears , please investigate it .
> > 
> > The cause of this problem is unknown and cannot be solved at this time, help from others is needed
> 
> Also most of the working configs are not working in anivu that work in official mpv amd aniyomi mpv , for example only sub-ass-* high level comands work sub-* dont work also osd comands don't work , for example osd-level and osd-fractions

--sub-ass-override=force will disappear the subtitles

**Comment by Luffyirl** [comment]
> > @SkyD666 Downloaded beta24 just now . When i enable subtitle styling the subtitle disappears , please investigate it .
> 
> The cause of this problem is unknown and cannot be solved at this time, help from others is needed

Ohh , ic are u using the old version of 1.15.n ?  jimir1 updated that yesterday coz the old 1.15.n was broken

**Comment by SkyD666** [comment]
> > > @SkyD666 Downloaded beta24 just now . When i enable subtitle styling the subtitle disappears , please investigate it .
> > 
> > The cause of this problem is unknown and cannot be solved at this time, help from others is needed
> 
> Ohh , ic are u using the old version of 1.15.n ?  jimir1 updated that yesterday coz the old 1.15.n was broken

1.14 is not work too😭
