### ISSUE TITLE
Ability to group feeds , and a all feeds in the list .

### ISSUE THREAD

**Issue by Luffyirl** [SkyD666/AniVu#13]
If we can group multiple rss in groups it would be really good for managing a large number of feeds . And a all feeds in list will help view everything at once . Example - [ReadYou ](https://github.com/Ashinch/ReadYou)
![Screenshot_2024-04-16-14-51-27-697_me ash reader](https://github.com/SkyD666/AniVu/assets/128812994/a7ac3e30-2bd6-48f4-9ff8-bad6b64f77eb)
![Screenshot_2024-04-16-14-51-20-853_me ash reader](https://github.com/SkyD666/AniVu/assets/128812994/3bf8fe3b-fb91-45af-9359-528a7cc1725d)
![Screenshot_2024-04-16-14-57-48-021_me ash reader](https://github.com/SkyD666/AniVu/assets/128812994/e22ff88d-ff39-4898-91eb-de41db657715)

**Comment by SkyD666** [comment]
https://github.com/SkyD666/AniVu/commit/b6634cdd10987b7f36c406157ca28aa5ff9a60d5
