### ISSUE TITLE
Ability to import opml files for mass rss feeds 

### ISSUE THREAD

**Issue by Luffyirl** [SkyD666/AniVu#14]
I have a good amount of torrent feeds in a normal rss feed app which if I want to import one by one it will be so much time consuming and tiring long process. if opml import support is added it will be so convenient.

**Comment by Ripl0gic** [comment]
Please add this feature, I have so many feeds it's the  reason I haven't yet switched to anivu yet from feeder+aria2app.Also the renaming and grouping feature,They have high priority too but opml import is urgently needed .
