### ISSUE TITLE
Option to directly download magnet /torrents 

### ISSUE THREAD

**Issue by P0bo** [SkyD666/AniVu#16]
Please give an option to directly download magnet links or torrent files we have. For old torrent files, RSS isn't really an option, so we need to use the magnet link and download the file with some torrent client. Since AniVu already supports downloading torrents, it would be great to be able to download magnet links/torrent files.

>An idea of how it may look like 
![Screenshot_2024-04-20-00-50-45-435_com skyd anivu](https://github.com/SkyD666/AniVu/assets/154865357/5c999888-c446-42f3-a5aa-102a1af86a4e)
![1713556545208](https://github.com/SkyD666/AniVu/assets/154865357/422b93fc-d77b-470e-8031-c3f6a19a8ba9)
![1713556544771](https://github.com/SkyD666/AniVu/assets/154865357/dae9b86b-156c-4edb-a08b-769582e1995e)
![1713556691247](https://github.com/SkyD666/AniVu/assets/154865357/d7d90ad4-dfaa-4995-8709-bc79068f6e6b)

**Comment by SkyD666** [comment]
https://github.com/SkyD666/AniVu/commit/b6634cdd10987b7f36c406157ca28aa5ff9a60d5
