### ISSUE TITLE
Option to hide the duplicate title present in description

### ISSUE THREAD

**Issue by P0bo** [SkyD666/AniVu#17]
The duplicate title takes up space in description and sometimes w cant see important details because of that . [More information here](https://github.com/Ashinch/ReadYou/issues/684)
>Anivu 
![Screenshot_2024-04-20-01-56-53-141_com skyd anivu](https://github.com/SkyD666/AniVu/assets/154865357/5bae612a-25a3-4980-8504-c015d583b5e4)

**Comment by P0bo** [comment]
Since you added the [Question](https://github.com/SkyD666/AniVu/labels/question) tag, I'm going to elaborate a bit more.

So basically, when a name is too long, we can't see important details in the description, such as size or category.

>![Screenshot_2024-04-20-15-08-09-101_com skyd anivu-edit](https://github.com/SkyD666/AniVu/assets/154865357/e48c64fb-02ac-4a4c-8a1b-edb3bd83fb2d)
See this one? The name is so long that it takes up the entire space meant for the description, and we can't see the size and category tags.

**Comment by SkyD666** [comment]
https://github.com/SkyD666/AniVu/actions/runs/8783737264
