### ISSUE TITLE
Option to hide infohash from description 

### ISSUE THREAD

**Issue by P0bo** [SkyD666/AniVu#23]
Like #17 , it'd be great if we could hide infohash from the description ![Screenshot_2024-04-26-23-59-54-718_org.cromite.cromite-edit.jpg](https://github.com/SkyD666/AniVu/assets/154865357/3351baa5-91a5-4f7e-8e47-113ab74b2f48)

![Screenshot_2024-04-27-00-00-25-398_com.skyd.anivu-edit.jpg](https://github.com/SkyD666/AniVu/assets/154865357/bfc29e1e-ac41-4829-9fb0-779d85a33729)

**Comment by SkyD666** [comment]
It seems that the nyaa tag is custom, and the standard RSS should not support this. In addition, the function that displays tags may also parse the nyaa tag to obtain data.

**Comment by P0bo** [comment]
> It seems that the nyaa tag is custom, and the standard RSS should not support this. In addition, the function that displays tags may also parse the nyaa tag to obtain data.

Ic man thanks for pointing out , Should I cloe the issue ?

**Comment by SkyD666** [comment]
> > It seems that the nyaa tag is custom, and the standard RSS should not support this. In addition, the function that displays tags may also parse the nyaa tag to obtain data.
> 
> Ic man thanks for pointing out , Should I cloe the issue ?

ok
