### ISSUE TITLE
Mark as seen

### ISSUE THREAD

**Issue by Luffyirl** [SkyD666/AniVu#27]
It will be efficient If we could see which torrents we have already seen in the torrents page/article page 

>A dimmed colour to mark as read could be added ![Screenshot_2024-04-28-04-48-26-162_me.ash.reader-edit.jpg](https://github.com/SkyD666/AniVu/assets/128812994/9488325c-2285-461a-bab9-1d9f648c50ef)

>Or a simple dot in front of the torrents which we haven't read could also be added 
![Screenshot_2024-04-28-04-56-18-032_com.prof18.feedflow-edit.jpg](https://github.com/SkyD666/AniVu/assets/128812994/03ee5eae-86ce-4d22-8a84-05a75a4668d1)

**Comment by P0bo** [comment]
A swipe right to mark read/unread would be handy

**Comment by SkyD666** [comment]
This requirement seems to be implemented, so close it
