### ISSUE TITLE
Grouping Media , and all media  in the media tab .

### ISSUE THREAD

**Issue by Luffyirl** [SkyD666/AniVu#28]
Like #13 If the download videos are grouped in the media based on which feed we download them from ,it will be really handy. Also a all media option to access all of downloaded media is also needed.

I have 6-7 currently airing anime as my rss feed separately so if the download media is organised based on the feed I have downloaded the media from it will be really organised and easy to access.

**Comment by SkyD666** [comment]
The current download function does not record feed information, and manually adding downloads cannot record it either.

**Comment by Luffyirl** [comment]
Like the article feed , u can have a default section where ones download with magnet links will get saved

**Comment by Bubblekey** [comment]
Is there any update on this ? . I'd really like to have this feature. I have downloaded too many episodes from different feeds and ripping groups now is getting harder for me to navigate between them because they are not categorised.


I recommend having the same layout as the feed page just show downloaded videos instead of torrents/articles after tapping a rss feed.

**Comment by SkyD666** [comment]
I think media groups and feed groups are separated from each other is better. Because of the possibility of grouping the same type of anime together

**Comment by Bubblekey** [comment]
Anything will be great, I'm happy as long as incan group the media and have group title , icon and description for that group.

**Comment by P0bo** [comment]
Here is the concept that I made . It needs to be  examined by the dev before he can implement it 

![Concept](https://github.com/SkyD666/AniVu/assets/154865357/53daa5fc-cdb5-43cc-ba8d-4a68db7f6f5d)

**Comment by Ripl0gic** [comment]
Hello dev , I'd also love my media to be well Grouped and want this kind or well organised layout,the app development is turning out really good , i also like that u are making progress towards switching the player to mpv . Are u planning to redesign the media tab or are u gonna be leaving as it is .

**Comment by Ripl0gic** [comment]
> Here is the concept that I made . It needs to be  examined by the dev before he can implement it 
> 
> ![Concept](https://github.com/SkyD666/AniVu/assets/154865357/53daa5fc-cdb5-43cc-ba8d-4a68db7f6f5d)
> 
> 

I love the suggestion but I'd like to add a small detail for those who download multiple anime from same feed , give the ability to create media group also ability to move media from one group easily. So if someone downloaded  two different anime from a single feed they can create another media  group and move one to there .

**Comment by SkyD666** [comment]
@Ripl0gic I will redesign the media page

**Comment by Ripl0gic** [comment]
Thank u very much dev , appreciate it.

**Comment by cauxar** [comment]
Ohh cool to see an engaging dev . Keep it up ♥️

**Comment by SkyD666** [comment]
Media library implementation details moved to: https://github.com/SkyD666/AniVu/issues/70
