### ISSUE TITLE
Hide Default group when its empty 

### ISSUE THREAD

**Issue by P0bo** [SkyD666/AniVu#31]
Hide the categories when the category has no rss feed in them , including the default catagory , i dont have single feed in that catagory

**Comment by SkyD666** [comment]
I feel this feature may cause misunderstanding, because users may not know that a group is hidden.

**Comment by P0bo** [comment]
Then only for default feed group add this option in
 >Settings>Appearance & Style >Feed screen>
>![1714305750028.jpg](https://github.com/SkyD666/AniVu/assets/154865357/a99db4dc-d0df-47a0-b21b-412df24c0e86)

**Comment by SkyD666** [comment]
https://github.com/SkyD666/AniVu/commit/72ce2e490205800904be2e49dc3336022b88f519
