### ISSUE TITLE
Revamp feed screen

### ISSUE THREAD

**Issue by P0bo** [SkyD666/AniVu#32]
Add padding , rounded corner etc .

>Here is a concept based on current anivu 
>![1714305184832.jpg](https://github.com/SkyD666/AniVu/assets/154865357/b327c4f7-1a28-4dd2-baf0-da18c1c55b4b)

**Comment by Bubblekey** [comment]
I also think revamp would look better, the current one looks really badly padded and doesn't match the ui of the app greatly. 

The concept is really good, imean the big icons and description styles but for padding I think open card and close carded like read you would be far more better looking yet simple .

>![1714396819399.jpg](https://github.com/SkyD666/AniVu/assets/168320211/b852a1a4-8e6c-4fe5-ab53-5783c421309a)

**Comment by P0bo** [comment]
Damn , tried to add those to the picture u shared , it does look great 
![1714398060403.jpg](https://github.com/SkyD666/AniVu/assets/154865357/21adf374-c191-4690-badd-86e049bee1a9)

**Comment by Bubblekey** [comment]
Bro the category is github, and the feeds are anime 😂😂

But this does look super clean and well designed

**Comment by P0bo** [comment]
Ok I fixed it 😂![1714399902158.jpg](https://github.com/SkyD666/AniVu/assets/154865357/898bb0b0-2c46-4463-a4ba-8115efe34be9)

**Comment by Ripl0gic** [comment]
> Ok I fixed it 😂😂![1714399946714.jpg](https://github.com/SkyD666/AniVu/assets/154865357/1a183d57-f582-44e0-8c0c-f657be1dec8a)
> 
> 

This one looks much more clean , I really hope dev implements something like this , I don't really like the current feed screen it feels like an app from 2019.

**Comment by SkyD666** [comment]
https://github.com/SkyD666/AniVu/commit/3d64e462df41986ac2180df28f2a33bbc22fc757
