### ISSUE TITLE
Option to have FAB as dynamic button in navigation bar.

### ISSUE THREAD

**Issue by Bubblekey** [SkyD666/AniVu#37]
![1714487306887.jpg](https://github.com/SkyD666/AniVu/assets/168320211/f84ae262-5e8b-4fe9-a999-3f575e4847ed)

**Comment by Bubblekey** [comment]
My concept image is kinda rough, [this](https://m3.material.io/components/bottom-app-bar) for better idea. But this doesn't give the overview for the dynamic button tho ,but u get the idea.

**Comment by SkyD666** [comment]
This is navigation bar, not bottom bar

**Comment by SkyD666** [comment]
https://m3.material.io/components/bottom-app-bar/guidelines#726acecd-8368-4c8d-9614-deefb20fc516
