### ISSUE TITLE
Better group selection and Edit feed 

### ISSUE THREAD

**Issue by Bubblekey** [SkyD666/AniVu#38]
https://github.com/SkyD666/AniVu/assets/168320211/e7bae105-709a-4a4c-a6be-c6f1dbe55af8

**Comment by SkyD666** [comment]
Does the current version meet your requirements?

https://github.com/SkyD666/AniVu/actions/runs/9315596495

**Comment by Bubblekey** [comment]
A more easier way to edit the feed name,link , description or move the feed would be really appreciated . Currently i lost count how many times i clicked delete 😭 instead of moving/editing the feed . The readyou edit style is really great , - if something similar is implemented it would be helpful.

**Comment by SkyD666** [comment]
![Screenshot_20240531_212252_com.skyd.anivu.jpg](https://github.com/SkyD666/AniVu/assets/32453770/62d1728a-867a-400d-9fc2-4e8c30b60c7c)

![Screenshot_20240531_212248_com.skyd.anivu.jpg](https://github.com/SkyD666/AniVu/assets/32453770/3b146cb2-008c-40c1-b3d1-2a9fcf7cc25d)

Is there anything inconvenient now?

**Comment by Bubblekey** [comment]
> ![Screenshot_20240531_212252_com.skyd.anivu.jpg](https://github.com/SkyD666/AniVu/assets/32453770/62d1728a-867a-400d-9fc2-4e8c30b60c7c)
> 
> ![Screenshot_20240531_212248_com.skyd.anivu.jpg](https://github.com/SkyD666/AniVu/assets/32453770/3b146cb2-008c-40c1-b3d1-2a9fcf7cc25d)
> 
> Is there anything inconvenient now?

Yes the remove button, while quickly trying to edit multiple feeds i mis touched it many times , which led me to add the feed again .

A unified edit + see details  option like readyou would prevent mistouch  and save an extra click

**Comment by SkyD666** [comment]
Perhaps a confirming dialog should pop up before deletion?

**Comment by Bubblekey** [comment]
A unified edit screen would be great, and particularly for groups i think u should show all groups like this ![Screenshot_2024-05-31-20-38-35-398_xyz.jmir.tachiyomi.mi.debug-edit.jpg](https://github.com/SkyD666/AniVu/assets/168320211/2ef86399-1ead-4cfe-bfd8-1ae15746e7e3)

The selected ome would fill

**Comment by Bubblekey** [comment]
The drop down menu requires clicking then swiping down then clicking, this would make that only one click

**Comment by Bubblekey** [comment]
U can hold a poll in discord to see which is better editing option read you or the anivu one .
Im in discord I'll vote.

**Comment by SkyD666** [comment]
> U can hold a poll in discord to see which is better editing option read you style or the anivu one . Im in discord I'll vote.

Most of the time I'm on Telegram

**Comment by Bubblekey** [comment]
> 
> > U can hold a poll in discord to see which is better editing option read you style or the anivu one . Im in discord I'll vote.
> 
> Most of the time I'm on Telegram

Then u can hold  there , ill join

**Comment by Bubblekey** [comment]
Closing this issue as i think #50 is perfect.
