### ISSUE TITLE
Blur

### ISSUE THREAD

**Issue by Bubblekey** [SkyD666/AniVu#41]
Give us blurred top and bottom. They look so cool 

>AniVu
![1](https://github.com/SkyD666/AniVu/assets/168320211/9306d576-3bfd-4f91-a7af-586ba4a4bb05)

>Teligram 
![2](https://github.com/SkyD666/AniVu/assets/168320211/9e2c9b8a-6535-46da-8937-193623f402eb)

>[M3U Android](https://github.com/oxyroid/M3UAndroid)
![3](https://github.com/SkyD666/AniVu/assets/168320211/f3bbb84b-9938-4e56-a83d-9678d4c161fc)

**Comment by SkyD666** [comment]
I still don't think this requirement is convincing enough, so close it, if you have a new suggestion please reopen it

**Comment by Bubblekey** [comment]
> I still don't think this requirement is convincing enough and it drains device performance, so close it, if you have a new suggestion please reopen it

I don't know gow to re open it , but i have a suggestion, 
Can we have hide top and bottom on scroll? 
Like chrome when scrolling down the link field etc hides automatically? Then if scrolled up it shows again ?

**Comment by SkyD666** [comment]
> > I still don't think this requirement is convincing enough and it drains device performance, so close it, if you have a new suggestion please reopen it
> 
> I don't know how to re open it , but i have a suggestion, Can we have hide top and bottom on scroll? Like chrome when scrolling down the link field etc hides automatically? Then if scrolled up it shows again ?

Maybe I'll give it a try.
