### ISSUE TITLE
External subtitle 

### ISSUE THREAD

**Issue by Ripl0gic** [SkyD666/AniVu#43]
Im watching this chinese anime which doesn't have English subtitles embedded, please add external subs so that we can choose download subtitle files .

**Comment by Luffyirl** [comment]
![subtitle](https://github.com/SkyD666/AniVu/assets/128812994/09c02199-8d0e-440e-b18d-4ba94624ad4a)

**Comment by SkyD666** [comment]
can you give me a subtitle file?
