### ISSUE TITLE
Redesign "edit feed" And "add feed" Layout 

### ISSUE THREAD

**Issue by P0bo** [SkyD666/AniVu#50]
![2024-06-01_01 02 20](https://github.com/SkyD666/AniVu/assets/154865357/cb2e1a1e-27cc-4ff7-a0e1-4519e72b57e4)

#### 1. Preview Section
- **Description**: This section includes the icon, name, and description of the item. It serves as an initial preview.
- **Functionality**:
  - On first opening with a long press, it shows as a preview.
  - Users can click on specific fields (icon, name, or description) to enter edit mode for that specific field.

#### 2. Link Section
- **Description**: This section handles link previews and editing.
- **Functionality**:
  - **Link Preview**:
    - Only the first part of the link is shown, even if the link is long.
    - A link logo on the left side provides quick access to the link.
  - **Interaction**:
    - Clicking the link logo opens the link in the browser.
    - Clicking the link field opens an editor where the entire link can be viewed and edited.

#### 3. Options Section
- **Description**: This section contains all the options and operations related to the feed.
- **Functionality**:
  - **Delete Feed**:
    - Has a special red icon for caution.
    - Clicking it prompts a warning dialog for confirmation.
  - **Additional Features** (future implementation):
    - **Notifications**: Enable/disable notifications.
    - **Auto-Download**: Enable/disable auto-download or set auto-download rules.

#### 4. Group Section
- **Description**: This section allows for convenient and fast group switching.
- **Functionality**:
  - **Group Display**:
    - Groups are shown as pills for one-click switching.
  - **Adding New Groups**:
    - Clicking the plus icon reveals a text field to add a new group.

**Comment by P0bo** [comment]
### Request for Improved Add Feed Feature in RSS Feed App

#### Current Issues
- The current "Add Feed" option is cluttered and asks for name, link, and group in one go.

#### Proposed Improvements
**Simplified Initial Input**:
   - **Step 1**: Only ask for the link in the initial step.
   - **Step 2**: Process the link to fetch feed details and provide this edit feed option , where user will edit a option if he wants to . 


This two-step process will streamline the addition of new feeds and improve the user experience by organizing the input fields more logically.

**Comment by P0bo** [comment]
![Screenshot_2024-06-01-08-09-11-94_8e19b33f15edabec7642d2a4e01a4872](https://github.com/SkyD666/AniVu/assets/154865357/40d455e0-0f8d-401c-8faa-149f58e02ec2)

**Comment by P0bo** [comment]
![Screenshot_2024-06-01-08-10-44-786_com.skyd.anivu-edit.jpg](https://github.com/SkyD666/AniVu/assets/154865357/48bec41a-736a-4482-a990-52bdfb2f364b)

![Screenshot_2024-06-01-08-10-55-429_com.skyd.anivu-edit.jpg](https://github.com/SkyD666/AniVu/assets/154865357/69c86d39-b80b-4fbc-bf9f-3037e17d7af5)

I noticed that the app doesn't show anything if the user doesn't add name while adding or editing . It should show the default name so that if the user wants to edit a part of the name that would be convenient.

**Comment by SkyD666** [comment]
https://github.com/SkyD666/AniVu/commit/df36159db08b9527ab73cbec5260f3a676e628bd
