### ISSUE TITLE
Rss parsing issue

### ISSUE THREAD

**Issue by P0bo** [SkyD666/AniVu#54]
https://feeds.megaphone.fm/STU4418364045
![Screenshot_2024-06-04-21-50-28-286_me.ash.reader-edit.jpg](https://github.com/SkyD666/AniVu/assets/154865357/1faff47b-b6ff-4413-9c0a-3e3a7d4be3b1)

![Screenshot_2024-06-04-21-49-58-785_com.skyd.anivu-edit.jpg](https://github.com/SkyD666/AniVu/assets/154865357/067ef5df-3ee3-403a-a2a0-bfd012d1ff63)

![Screenshot_2024-06-04-21-50-53-254_com.skyd.anivu-edit.jpg](https://github.com/SkyD666/AniVu/assets/154865357/1716188d-de56-463c-a4a4-444982ffd16e)

![Screenshot_2024-06-04-21-50-35-204_me.ash.reader-edit.jpg](https://github.com/SkyD666/AniVu/assets/154865357/88a7de74-ddfa-4a53-8972-0d4fa57e89ff)

**Comment by P0bo** [comment]
![Screenshot_2024-06-04-22-26-49-517_com.skyd.anivu-edit.jpg](https://github.com/SkyD666/AniVu/assets/154865357/9e352878-d8f2-4e59-a3c7-681e2ef60c3b)

![Screenshot_2024-06-04-22-26-24-093_me.ash.reader-edit.jpg](https://github.com/SkyD666/AniVu/assets/154865357/0b1d77d4-39ba-42bc-82d4-30d2d9bbf93a)

https://www.androidpolice.com/feed/

**Comment by SkyD666** [comment]
For the image issue, this RSS puts the image in the enclosure tag

**Comment by P0bo** [comment]
> For the image issue, this RSS puts the image in the enclosure tag

The thing is anivu does not have a option parse full content like read you . So we don't get the full content 





![Screenshot_2024-06-05-21-50-08-020_me.ash.reader-edit.jpg](https://github.com/SkyD666/AniVu/assets/154865357/ea3d6c3a-3a15-4040-929e-0dda7a2f6f90)

![Screenshot_2024-06-05-21-50-20-089_me.ash.reader.jpg](https://github.com/SkyD666/AniVu/assets/154865357/c2a13070-bb29-463d-8f1f-ae0e14e7a9c4)

**Comment by SkyD666** [comment]
I will check it tomorrow

**Comment by P0bo** [comment]
Have you checked?

**Comment by SkyD666** [comment]
no

**Comment by P0bo** [comment]
I see , please do when u are free

**Comment by SkyD666** [comment]
ok
