### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by codenyte** [SkyD666/AniVu#59]

**Comment by linsui** [comment]
@SkyD666 SInce you added "help wanted" label, can I package this app for F-Droid?

**Comment by SkyD666** [comment]
> @SkyD666 SInce you added "help wanted" label, can I package this app for F-Droid?

One problem is the signature issue. Currently, the release package signature is not public.

**Comment by linsui** [comment]
I'm not sure what you mean. Do you not want the apk to be signed by F-Droid?

**Comment by SkyD666** [comment]
> I'm not sure what you mean. Do you not want the apk to be signed by F-Droid?

I'd like to use my private signature, but F-Droid doesn't seem to be able to use private signatures

**Comment by linsui** [comment]
F-Droid can't use your private key but we can try [reproducible build](https://f-droid.org/docs/Reproducible_Builds/).

**Comment by SkyD666** [comment]
> F-Droid can't use your private key but we can try [reproducible build](https://f-droid.org/docs/Reproducible_Builds/).

Please try it, I'd appreciate it. 🥰

**Comment by linsui** [comment]
Reproducible build works for 1.0. Can you provide an apk built from latest commit? Then I'll open a PR adding fastlane structure. Currently you only published the arm64 apk. Do you want to publish other arches?

**Comment by SkyD666** [comment]
> Reproducible build works for 1.0. Can you provide an apk built from latest commit? Then I'll open a PR adding fastlane structure. Currently you only published the arm64 apk. Do you want to publish other arches?

See here: https://github.com/SkyD666/AniVu/actions/runs/10121220611

**Comment by linsui** [comment]
It's reproducible. I'll open a PR for fastlane.

**Comment by linsui** [comment]
Different abis should have different version code. Can you make them 181, 182, 183, 184?

**Comment by SkyD666** [comment]
> Different abis should have different version code. Can you make them 181, 182, 183, 184?

What does “181, 182, 183, 184” mean?

**Comment by linsui** [comment]
Currently the version code of every abi is 18. We need to set different version code for different abi, i.e., 181 for arm, 182 for arm64, 183 for x86, 184 for x64.

**Comment by SkyD666** [comment]
> Currently the version code of every abi is 18. We need to set different version code for different abi, i.e., 181 for arm, 182 for arm64, 183 for x86, 184 for x64.

Does fdroid require different version numbers for different abi?

**Comment by linsui** [comment]
Yes, F-Droid requires different apk has different version code.

**Comment by SkyD666** [comment]
> Yes, F-Droid requires different apk has different version code.

Is there an official documentation for this?

**Comment by linsui** [comment]
https://developer.android.com/build/configure-apk-splits#configure-APK-versions

**Comment by SkyD666** [comment]
> https://developer.android.com/build/configure-apk-splits#configure-APK-versions

Let's just upload the arm64 one for now. Changing the version number will cause the update logic to be changed as well, which is troublesome.

**Comment by linsui** [comment]
No problem. Could you please release a new version?

**Comment by SkyD666** [comment]
> No problem. Could you please release a new version?

Can I do it tomorrow? It's the middle of the night here.

**Comment by linsui** [comment]
Of course. No hurry.

**Comment by SkyD666** [comment]
> Of course. No hurry.

https://github.com/SkyD666/AniVu/releases/tag/19

**Comment by linsui** [comment]
It will be available on F-Droid in few days.

**Comment by SkyD666** [comment]
> It will be available on F-Droid in few days.

thank you very much

**Comment by linsui** [comment]
Do you consider publishing your other apps on F-Droid? :)

**Comment by SkyD666** [comment]
> Do you consider publishing your other apps on F-Droid? :)

I have this plan, but I want to see the effect of anivu first

**Comment by SkyD666** [comment]
> Do you consider publishing your other apps on F-Droid? :)

It seems that it has not appeared in fdroid for several days. I wonder if there is any problem.

**Comment by linsui** [comment]
It will be published as soon as the index is signed.

You can check the status on https://monitor.f-droid.org/builds.

**Comment by SkyD666** [comment]
> It will be published as soon as the index is signed.
> 
> You can check the status on https://monitor.f-droid.org/builds.

thanks

**Comment by linsui** [comment]
It has been published. :)

**Comment by SkyD666** [comment]
> Do you consider publishing your other apps on F-Droid? :)

Please help me post [Rays](https://github.com/SkyD666/Rays-Android) to F-Droid as well, thanks a lot! 🥰

**Comment by linsui** [comment]
Will do. :)

**Comment by linsui** [comment]
Looks like we can't package Rays currently. How about packaging Raca first?

**Comment by SkyD666** [comment]
> Looks like we can't package Rays currently. How about packaging Raca first?

ok

**Comment by SkyD666** [comment]
> Could you please release a new version for Raca?

ok

**Comment by linsui** [comment]
@SkyD666 

We find that there is a `DependencyInfoBlock` in your APK.

It's a [Signing block](https://source.android.com/docs/security/features/apksigning/v2#apk-signing-block) added by AGP and encrypted with the Google public key so it can't be read by anyone else except Google. You can read more about it [here](https://gitlab.com/fdroid/admin/-/issues/367), [here](https://gitlab.com/fdroid/fdroidserver/-/issues/1056) and [here](https://android.izzysoft.de/articles/named/iod-scan-apkchecks?lang=en#blobs).

While this was added a while ago, we were only enforcing it for new apps, and recently we started scanning updates too.

Could you please disable it with the following code?

```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

Thanks!

**Comment by SkyD666** [comment]
> [@SkyD666](https://github.com/SkyD666)
> 
> We find that there is a `DependencyInfoBlock` in your APK.
> 
> It's a [Signing block](https://source.android.com/docs/security/features/apksigning/v2#apk-signing-block) added by AGP and encrypted with the Google public key so it can't be read by anyone else except Google. You can read more about it [here](https://gitlab.com/fdroid/admin/-/issues/367), [here](https://gitlab.com/fdroid/fdroidserver/-/issues/1056) and [here](https://android.izzysoft.de/articles/named/iod-scan-apkchecks?lang=en#blobs).
> 
> While this was added a while ago, we were only enforcing it for new apps, and recently we started scanning updates too.
> 
> Could you please disable it with the following code?
> 
> ```
> android {
>     dependenciesInfo {
>         // Disables dependency metadata when building APKs.
>         includeInApk = false
>         // Disables dependency metadata when building Android App Bundles.
>         includeInBundle = false
>     }
> }
> ```
> 
> Thanks!

Hi, I want to know if I can apply this configuration only for the F-Droid Variant

**Comment by linsui** [comment]
Or course! :)

**Comment by SkyD666** [comment]
> Or course! :)

I'm not very familiar with this, the code below seems incorrect, could you please tell me how to modify it?

```kotlin
android {
    ...
    flavorDimensions += "version"
    productFlavors {
        create("GitHub") {
            dimension = "version"
        }
        create("FDroid") {
            dimension = "version"
            dependenciesInfo {
                // Disables dependency metadata when building APKs.
                includeInApk = false
                // Disables dependency metadata when building Android App Bundles.
                includeInBundle = false
            }
        }
    }
    ...
```

**Comment by linsui** [comment]
No, I don't know how to do that...

**Comment by SkyD666** [comment]
> No, I don't know how to do that...

Can you tell me your email address so I can send you the build product of the FDroid version? I can't upload files in the Issue, the GitHub page says the upload failed

**Comment by linsui** [comment]
You can change the extension to zip to upload it here. But can you put it in release?

**Comment by SkyD666** [comment]
[PodAura_3.0_arm64-v8a_release_FDroid.zip.001.zip](https://github.com/user-attachments/files/18464471/PodAura_3.0_arm64-v8a_release_FDroid.zip.001.zip)
[PodAura_3.0_arm64-v8a_release_FDroid.zip.002.zip](https://github.com/user-attachments/files/18464472/PodAura_3.0_arm64-v8a_release_FDroid.zip.002.zip)
[PodAura_3.0_arm64-v8a_release_FDroid.zip.003.zip](https://github.com/user-attachments/files/18464473/PodAura_3.0_arm64-v8a_release_FDroid.zip.003.zip)
[PodAura_3.0_arm64-v8a_release_FDroid.zip.004.zip](https://github.com/user-attachments/files/18464470/PodAura_3.0_arm64-v8a_release_FDroid.zip.004.zip)

GitHub does not allow uploading files larger than 10MB, so I compressed them in multiple volumes.

**Comment by SkyD666** [comment]
ok

**Comment by SkyD666** [comment]
> F-Droid fetches the apk from a url. https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.skyd.anivu.yml#L16 So you need to put the apk in the release.

https://github.com/SkyD666/PodAura/releases/download/25/PodAura_3.0_arm64-v8a_release_GitHub.apk

**Comment by linsui** [comment]
The new apk still has the Dependency metadata block.

**Comment by SkyD666** [comment]
> The new apk still has the Dependency metadata block.

But I should have added that configuration

**Comment by linsui** [comment]
Sorry, I scanned the wrong version. The block has been removed. Thanks!

**Comment by SkyD666** [comment]
> Sorry, I scanned the wrong version. The block has been removed. Thanks!

Can you help update the app name, screenshots and description text in F-Droid?

**Comment by linsui** [comment]
The are fetched from https://github.com/SkyD666/PodAura/tree/master/fastlane/metadata/android automatically.

**Comment by SkyD666** [comment]
> The are fetched from https://github.com/SkyD666/PodAura/tree/master/fastlane/metadata/android automatically.

OK, I will update these files. Do I just need to wait after the update?

**Comment by linsui** [comment]
The fastlane metadata is fetched from the commit used to build the app. So you need to update it first, then I update the build metadata.

**Comment by SkyD666** [comment]
> The fastlane metadata is fetched from the commit used to build the app. So you need to update it first, then I update the build metadata.

Can this file be in svg format?

fastlane/metadata/android/en-US/images/icon.png

**Comment by linsui** [comment]
Only png/jpg is supported.

**Comment by SkyD666** [comment]
> Only png/jpg is supported.

https://github.com/SkyD666/PodAura/commit/73f684d219f6dba38835f46d7b494bda12d7292a

If you need the mapping.txt file, use this: https://github.com/SkyD666/PodAura/releases/download/25/mapping-2.zip

**Comment by linsui** [comment]
Can you build the apk with GHA? The apk built on windows has different new line. And the baseline.prof file is also not reproducible. And the vcs info is embeded in the apk so you need to build a new apk from the latest commit.

**Comment by SkyD666** [comment]
> Can you build the apk with GHA? The apk built on windows has different new line. And the baseline.prof file is also not reproducible. And the vcs info is embeded in the apk so you need to build a new apk from the latest commit.

https://github.com/SkyD666/PodAura/actions/runs/12845396719

**Comment by linsui** [comment]
It works, could you please update the apk in the release? Thanks!

**Comment by SkyD666** [comment]
> It works, could you please update the apk in the release? Thanks!

OK

**Comment by linsui** [comment]
Thanks!

**Comment by linsui** [comment]
https://github.com/Razeeman/Android-SimpleTimeTracker/commit/55e38a149df40966b401cee4a9a638d27db77bd9 An example disabling dependency info only for fdroid flavor.

**Comment by SkyD666** [comment]
> https://github.com/Razeeman/Android-SimpleTimeTracker/commit/55e38a149df40966b401cee4a9a638d27db77bd9 An example disabling dependency info only for fdroid flavor.

thanks
