### ISSUE TITLE
Unread count

### ISSUE THREAD

**Issue by P0bo** [SkyD666/AniVu#65]
A unread count beside the total article count to know how many new articles are in the feed . Will be useful to navigate to the feed that have new unread articles .
 

Example-
>Aniyomi
>![pic](https://github.com/SkyD666/AniVu/assets/154865357/2736100c-d1a7-40ed-acdd-0083ba2e200f)

**Comment by SkyD666** [comment]
https://github.com/SkyD666/AniVu/commit/02a7174cd877c65fdb9810af6438b535897b2851
