### ISSUE TITLE
Ability to open media from the cation picker and move location picker to right side 

### ISSUE THREAD

**Issue by P0bo** [SkyD666/AniVu#72]
https://github.com/user-attachments/assets/f8c4f36e-b1a0-438d-8b8f-43e37f3c922f
It will be great if we could play any file even if the folder is not selected  from the storage option , also the button in left side
 will be a handy addition  ,  users will be able to  play any video file even from inside anivu .

, and also if the position of button on location is moved to right side making 3 buttons in right side will look good and organised like articles page and the media title aligned to left side , just like article page .

**Comment by SkyD666** [comment]
[10b902d](https://github.com/SkyD666/AniVu/commit/10b902d115375dc3d17f7bd2fff6ab6ac4729ae4)
