### ISSUE TITLE
一些界面上的建议（MD3）

### ISSUE THREAD

**Issue by txyyh** [SkyD666/AniVu#8]
首先，还请调用Android系统动画，目前这个动画只是单纯的渐变实在不太好；
然后，作为一个md3 app，还请适配动态颜色。

另外，私认为 divider 用的太多了，订阅或者文章界面可以考虑试试 Card；然后更多界面图标很少，不太适合此类布局，可以试试 Navigation drawer，可能会好看点？

**Comment by SkyD666** [comment]
调用Android系统动画，指的是页面切换吗

**Comment by SkyD666** [comment]
对于最后一个建议，应该需要评估一下，原因请见：https://m3.material.io/components/cards/guidelines#406a4338-c187-4d1f-b289-502a79eb6b47 ------ Don't force content into cards when spacing, headlines, or dividers would create a simpler visual hierarchy

**Comment by txyyh** [comment]
那试试 spacing 
主要还是 divider 用的太多

**Comment by txyyh** [comment]
> 如果是的话，没有办法用系统的动画，因为这些页面是Fragment，不是Activity，系统的动画针对的是Activity

也许可以参考下还在使用fragment时期的tachi代码是如何实现的

**Comment by SkyD666** [comment]
> > 如果是的话，没有办法用系统的动画，因为这些页面是Fragment，不是Activity，系统的动画针对的是Activity
> 
> 也许可以参考下还在使用fragment时期的tachi代码是如何实现的

能给个地址吗

**Comment by txyyh** [comment]
随便一个taichi分支都有以前的历史提交，比如[这个](https://github.com/jobobby04/TachiyomiSY)

**Comment by SkyD666** [comment]
https://github.com/SkyD666/AniVu/assets/32453770/6259cd3d-2b7c-43d9-bc0d-b1df70dec079

您指的系统的切换效果是这种从右侧进入的效果吗

**Comment by txyyh** [comment]
> 您指的系统的切换效果是这种从右侧进入的效果吗

是的
您完全可以通过查看 android 14 的设置界面来参考最终效果

**Comment by SkyD666** [comment]
> 是的 您完全可以通过查看 android 14 的设置界面来参考最终效果

其实这个效果应该也不是跟随系统的，fragment切换也可以设置这样的动画

**Comment by SkyD666** [comment]
动态色与更换主题请见此处：https://github.com/SkyD666/AniVu/actions/runs/8558141909
