### ISSUE TITLE
Support for .torrent files

### ISSUE THREAD

**Issue by ghost** [SkyD666/AniVu#96]
There is no way to open .torrent files from a file manager

**Comment by SkyD666** [comment]
https://github.com/SkyD666/AniVu/actions/runs/12211225112

**Comment by SkyD666** [comment]
https://github.com/SkyD666/AniVu/actions/runs/12211371915/job/34068559713

**Comment by Korb** [comment]
![Screenshot_2024_1214_233030](https://github.com/user-attachments/assets/a65f429b-5b78-4c05-9195-bee617a4630c)

![Screenshot_20241214_233043](https://github.com/user-attachments/assets/24d85918-77e1-44a5-b194-71772ebf7def)

AniVu does not register itself in the OS as an application that opens .torrent-files, and when forced to open (`Play` command), it displays only an empty player window. The .torrent-file is not added to the download list.

AniVu 2.0 (19) at F-Droid
Added on 03/08/2024
Size: 26.2 MiB
Android: 7.0+

OS version: Funtouch OS 14
Model: Vivo T1 (4G, V2153)
Hardware version: MP_0.1
Build number: PD22010F_EX_A_14.2.10.1.W20
Baseband version: .HA.1.1.c2-00054-DIVAR_GENSP_PACK-1.29062.107
Kernel version: 4.19.157-perf+, 1 Fri Nov 15 11:50:50 CST 2024
Compile time: 15 Nov 2024 06:41:34
Android security update: 1 November 2024
Google Play system update: 1 October 2024
Software parameter update: 29 October 2024

Should I wait for an app update on F-Droid?

**Comment by SkyD666** [comment]
> ![Screenshot_2024_1214_233030](https://github.com/user-attachments/assets/a65f429b-5b78-4c05-9195-bee617a4630c)
> 
> ![Screenshot_20241214_233043](https://github.com/user-attachments/assets/24d85918-77e1-44a5-b194-71772ebf7def)
> 
> AniVu does not register itself in the OS as an application that opens .torrent-files, and when forced to open (`Play` command), it displays only an empty player window. The .torrent-file is not added to the download list.
> 
> AniVu 2.0 (19) at F-Droid
> Added on 03/08/2024
> Size: 26.2 MiB
> Android: 7.0+
> 
> OS version: Funtouch OS 14
> Model: Vivo T1 (4G, V2153)
> Hardware version: MP_0.1
> Build number: PD22010F_EX_A_14.2.10.1.W20
> Baseband version: .HA.1.1.c2-00054-DIVAR_GENSP_PACK-1.29062.107
> Kernel version: 4.19.157-perf+, 1 Fri Nov 15 11:50:50 CST 2024
> Compile time: 15 Nov 2024 06:41:34
> Android security update: 1 November 2024
> Google Play system update: 1 October 2024
> Software parameter update: 29 October 2024
> 
> Should I wait for an app update on F-Droid?

https://github.com/SkyD666/AniVu/actions/runs/12292756811
